'use strict';
const $=id=>document.getElementById(id),KEY='silva-reader-v1';
let data={stories:[],glossary:{}},state={progress:{},words:[],custom:[],size:25,night:false,last:null},view='all',active=null,page=0,speaking=false,selectedWord='';
try{const s=JSON.parse(localStorage.getItem(KEY));if(s&&typeof s==='object')state={...state,...s};}catch{}
const escapeHTML=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function toast(msg){$('toast').textContent=msg;$('toast').style.display='block';clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>$('toast').style.display='none',3000)}
function save(){try{localStorage.setItem(KEY,JSON.stringify(state))}catch{toast('设备空间不足，记录暂时无法保存。请导出备份。')}}
const stories=()=>[...data.stories,...state.custom];
const pages=s=>{const out=[];for(let i=0;i<s.paragraphs.length;i+=2)out.push(s.paragraphs.slice(i,i+2));return out};
function stopSpeech(){if('speechSynthesis'in window)speechSynthesis.cancel();speaking=false;const b=$('listen');if(b)b.textContent='听这一页'}
function applySettings(){document.body.classList.toggle('night',state.night);document.documentElement.style.setProperty('--read-size',state.size+'px')}
function speak(text){if(!('speechSynthesis'in window)){toast('当前浏览器不支持朗读');return}stopSpeech();const u=new SpeechSynthesisUtterance(text);u.lang='en-US';u.rate=.8;const voice=speechSynthesis.getVoices().find(v=>v.lang.startsWith('en')&&v.localService);if(voice)u.voice=voice;u.onend=u.onerror=()=>{speaking=false;const b=$('listen');if(b)b.textContent='听这一页'};speaking=true;speechSynthesis.speak(u);const b=$('listen');if(b)b.textContent='停止朗读'}
function bookStatus(s){const p=state.progress[s.id];return p?.done?'已读完':p?'读到第 '+(p.page+1)+' 页':'还没开始'}
function shelf(tab='all'){stopSpeech();active=null;view=tab;const all=stories(),done=all.filter(s=>state.progress[s.id]?.done).length,last=all.find(s=>s.id===state.last&&!state.progress[s.id]?.done);let list=tab==='done'?all.filter(s=>state.progress[s.id]?.done):all;
 $('app').innerHTML=`<div class="library-top"><div><span class="eyebrow">YOUR LITTLE READING WORLD</span><h1>我的英文书架</h1><p class="intro">选一个故事，开始今天的冒险。</p></div><span class="counter">已读完 ${done} / ${all.length} 篇</span></div>${last?`<section class="continue"><div><span class="eyebrow">KEEP READING</span><h2>${escapeHTML(last.title)}</h2><p>${bookStatus(last)} · Minecraft Stories</p></div><button data-open="${escapeHTML(last.id)}">继续阅读</button></section>`:''}<nav class="tabs" aria-label="书架分类"><button data-tab="all" class="${tab==='all'?'selected':''}">全部故事 ${all.length}</button><button data-tab="done" class="${tab==='done'?'selected':''}">已读完 ${done}</button><button data-tab="words" class="${tab==='words'?'selected':''}">生词本 ${state.words.length}</button></nav>${tab==='words'?renderWords():list.length?`<div class="grid">${list.map(s=>{const p=state.progress[s.id],progress=p?.done?100:p?Math.round(p.page/pages(s).length*100):0;const wc=s.paragraphs.join(' ').split(/\s+/).length;return `<button class="book" data-open="${escapeHTML(s.id)}"><div class="cover"><div class="cover-top"><span>${s.chapter?'MINECRAFT STORIES':'MY STORIES'}</span><span>ENGLISH</span></div><span class="chapter">${String(s.chapter||'').padStart(2,'0')}</span><div class="cover-title">${escapeHTML(s.title)}</div></div><div class="book-info"><h3>${escapeHTML(s.title)}</h3><div class="book-meta"><span>${wc} 词 · ${pages(s).length} 页</span><span>${bookStatus(s)}</span></div><div class="progress"><span style="width:${progress}%"></span></div></div></button>`}).join('')}</div>`:'<p class="empty">读完一个故事后，它会出现在这里。</p>'}`;
 $('app').querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>openStory(b.dataset.open));$('app').querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>shelf(b.dataset.tab));$('app').querySelectorAll('[data-vocab]').forEach(b=>b.onclick=()=>showWord(b.dataset.vocab));window.scrollTo(0,0)}
function renderWords(){return state.words.length?`<div class="word-grid">${state.words.map(w=>`<button class="word-card" data-vocab="${escapeHTML(w)}"><strong>${escapeHTML(w)}</strong><span>${escapeHTML(data.glossary[w]||'可以请家长一起查词')}</span></button>`).join('')}</div>`:'<p class="empty">阅读时点一个单词，再点“加入生词本”。你的新单词就会留在这里。</p>'}
function openStory(id){active=stories().find(s=>s.id===id);if(!active)return;page=Math.min(state.progress[id]?.page||0,pages(active).length-1);state.last=id;renderReader()}
function tokenize(p){return p.split(/([A-Za-z]+(?:['’][A-Za-z]+)?)/).map(t=>/^[A-Za-z]/.test(t)?`<span class="word ${data.glossary[t.toLowerCase()]?'known':''}" tabindex="0" role="button" data-word="${escapeHTML(t)}" aria-label="查看 ${escapeHTML(t)} 的释义">${escapeHTML(t)}</span>`:escapeHTML(t)).join('')}
function renderReader(){stopSpeech();const ps=pages(active);state.progress[active.id]={...state.progress[active.id],page};save();$('app').innerHTML=`<div class="reader-top"><button id="back" class="quiet">回到书架</button><div class="reader-tools"><button id="smaller" aria-label="减小字号">A−</button><button id="larger" aria-label="增大字号">A＋</button><button id="theme">${state.night?'白天':'夜间'}</button><button id="listen">听这一页</button></div></div><article class="reading-shell"><div class="story-heading"><span class="eyebrow">${active.chapter?'MINECRAFT · CHAPTER '+String(active.chapter).padStart(2,'0'):'MY STORY'}</span><h1>${escapeHTML(active.title)}</h1><p class="reader-hint">点单词查释义 · 虚线标出了故事中的重点词</p></div><div class="story-text">${ps[page].map(p=>'<p>'+tokenize(p)+'</p>').join('')}</div><div class="reader-bottom"><button id="prev" class="quiet" ${page===0?'disabled':''}>上一页</button><span class="page-number">${page+1} / ${ps.length}</span><button id="next">${page===ps.length-1?'读完了':'下一页'}</button></div></article><div class="reader-progress"><div class="progress"><span style="width:${Math.round((page+1)/ps.length*100)}%"></span></div></div>`;
 $('back').onclick=()=>shelf();$('prev').onclick=()=>{page--;renderReader();window.scrollTo(0,0)};$('next').onclick=()=>{if(page===ps.length-1)active.quiz?quiz():complete();else{page++;renderReader();window.scrollTo(0,0)}};$('smaller').onclick=()=>{state.size=Math.max(19,state.size-2);applySettings();save()};$('larger').onclick=()=>{state.size=Math.min(37,state.size+2);applySettings();save()};$('theme').onclick=()=>{state.night=!state.night;applySettings();save();$('theme').textContent=state.night?'白天':'夜间'};$('listen').onclick=()=>speaking?stopSpeech():speak(ps[page].join(' '));$('app').querySelectorAll('[data-word]').forEach(w=>{w.onclick=()=>showWord(w.dataset.word);w.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();showWord(w.dataset.word)}}})}
function showWord(w){selectedWord=w.toLowerCase();$('word-title').textContent=w;$('meaning').textContent=data.glossary[selectedWord]||'这篇故事没有附这个词的释义。你可以先结合上下文猜一猜，也可以加入生词本，和家长一起查。';$('save-word').textContent=state.words.includes(selectedWord)?'移出生词本':'加入生词本';$('word-dialog').showModal()}
function quiz(){stopSpeech();const q=active.quiz;$('app').innerHTML=`<button id="back-read" class="quiet">返回故事</button><article class="reading-shell"><span class="eyebrow">ONE LITTLE CHECK</span><h1>你读懂了吗？</h1><h2>${escapeHTML(q.question)}</h2><div class="quiz-options">${q.options.map((o,i)=>`<button data-answer="${i}">${escapeHTML(o)}</button>`).join('')}</div><p id="feedback" class="feedback">选一个答案。答错了也可以再读一遍。</p><button id="finish" hidden>完成阅读</button></article>`;$('back-read').onclick=renderReader;$('app').querySelectorAll('[data-answer]').forEach(b=>b.onclick=()=>{const correct=Number(b.dataset.answer)===q.answer;b.classList.add(correct?'correct':'wrong');$('feedback').textContent=correct?'答对了！这个故事已经读懂啦。':'再想一想，也可以返回故事找线索。';if(correct)$('finish').hidden=false});$('finish').onclick=complete;window.scrollTo(0,0)}
function complete(){state.progress[active.id]={page:pages(active).length-1,done:true,completedAt:new Date().toISOString()};save();$('app').innerHTML=`<article class="reading-shell finish"><div class="badge">✦</div><span class="eyebrow">STORY COMPLETE</span><h1>又读完了一个故事！</h1><p class="feedback">${escapeHTML(active.title)}</p><button id="finished-back">回到书架</button></article>`;$('finished-back').onclick=()=>shelf();window.scrollTo(0,0)}
document.querySelectorAll('.dialog-close').forEach(b=>b.onclick=()=>b.closest('dialog').close());$('home').onclick=()=>shelf();$('parents').onclick=()=>{$('parent-dialog').showModal()};$('say-word').onclick=()=>speak(selectedWord);$('save-word').onclick=()=>{if(state.words.includes(selectedWord))state.words=state.words.filter(w=>w!==selectedWord);else state.words.push(selectedWord);save();$('save-word').textContent=state.words.includes(selectedWord)?'移出生词本':'加入生词本';if(!active)shelf(view)};
$('import-story').onclick=()=>{const title=$('new-title').value.trim(),body=$('new-body').value.trim();if(!title||!body){$('parent-message').textContent='请填写标题和正文。';return}if(body.length>100000){$('parent-message').textContent='故事太长，请分成几篇添加。';return}const paras=body.split(/\n\s*\n/).map(p=>p.trim()).filter(Boolean);state.custom.push({id:'custom-'+Date.now()+'-'+Math.random().toString(36).slice(2,6),title,paragraphs:paras});save();$('new-title').value=$('new-body').value='';$('parent-dialog').close();shelf();toast('新故事已加入书架')};
$('backup').onclick=()=>{const blob=new Blob([JSON.stringify({format:'silva-reader-backup',version:1,state},null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='silva-reading-backup.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};
$('restore').onchange=async e=>{try{const file=e.target.files[0];if(!file)return;if(file.size>3000000)throw Error();const b=JSON.parse(await file.text()),s=b.state;if(b.format!=='silva-reader-backup'||!s||!Array.isArray(s.words)||!s.words.every(w=>typeof w==='string')||!Array.isArray(s.custom)||!s.custom.every(x=>typeof x.id==='string'&&typeof x.title==='string'&&Array.isArray(x.paragraphs)&&x.paragraphs.length&&x.paragraphs.every(p=>typeof p==='string'))||!s.progress||typeof s.progress!=='object')throw Error();if(!confirm('恢复备份将替换这台设备上的阅读记录和自建故事。继续吗？'))return;state={progress:s.progress,words:s.words,custom:s.custom,size:Math.max(19,Math.min(37,Number(s.size)||25)),night:!!s.night,last:s.last};save();applySettings();$('parent-dialog').close();shelf();toast('备份已恢复')}catch{$('parent-message').textContent='无法读取备份，请选择本工具导出的备份文件。'}finally{e.target.value=''}};
async function init(){applySettings();try{const r=await fetch('stories.json');if(!r.ok)throw Error();data=await r.json();shelf();if('serviceWorker'in navigator){const reg=await navigator.serviceWorker.register('sw.js');await navigator.serviceWorker.ready;const ready=()=>{const sw=navigator.serviceWorker.controller||reg.active;if(sw)sw.postMessage({type:'CHECK_OFFLINE'})};navigator.serviceWorker.addEventListener('message',e=>{if(e.data?.type==='OFFLINE_READY')$('offline').textContent='故事已保存，可离线阅读';if(e.data?.type==='OFFLINE_FAILED')$('offline').textContent='离线保存未完成，请联网重试'});navigator.serviceWorker.addEventListener('controllerchange',ready);ready()}else $('offline').textContent='请用 Safari 打开以保存离线故事';}catch{$('app').innerHTML='<div class="empty">故事暂时无法加载。首次使用请联网打开；如果已经保存离线故事，请重新打开主屏幕上的工具。</div>';$('offline').textContent='故事未加载'}}init();
