'use strict';
const $=id=>document.getElementById(id),KEY='silva-reader-v1';
let data={stories:[],glossary:{}},state={progress:{},words:[],custom:[],size:25,night:false,last:null},view='all',active=null,page=0,speaking=false,selectedWord='',speechText='';
try{const s=JSON.parse(localStorage.getItem(KEY));if(s&&typeof s==='object')state={...state,...s};}catch{}
const escapeHTML=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function toast(msg){$('toast').textContent=msg;$('toast').style.display='block';clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>$('toast').style.display='none',3000)}
function save(){try{localStorage.setItem(KEY,JSON.stringify(state))}catch{toast('设备空间不足，记录暂时无法保存。请导出备份。')}}
const stories=()=>[...data.stories,...state.custom];
const pages=s=>{if(s.picturePages)return s.picturePages.map(p=>[p.text]);const out=[];for(let i=0;i<s.paragraphs.length;i+=2)out.push(s.paragraphs.slice(i,i+2));return out};
const SENTENCE_TRANSLATE_ICON='T';
const SENTENCE_SPEAK_ICON='<svg viewBox="0 0 24 24" aria-hidden="true" focusable="false"><path d="M8 5.5 19 12 8 18.5Z" fill="currentColor"/></svg>';
const SENTENCE_STOP_ICON='<svg viewBox="0 0 24 24" aria-hidden="true" focusable="false"><rect x="7" y="7" width="10" height="10" rx="1.5" fill="currentColor"/></svg>';
let narrationPlayer=null,speechGeneration=0,speechClip=null,audioStopTimer=null;
function syncSpeechButtons(){const listen=$('listen');if(listen)listen.textContent=speaking?'停止朗读':'听这一页';const book=$('listen-book');if(book){const playing=speaking&&speechClip?.wholeBook;book.textContent=playing?'暂停朗读':(speechClip?.wholeBook&&narrationPlayer||state.bookAudio?.[active?.id]>0)?'继续朗读':'朗读整本';book.setAttribute('aria-pressed',String(!!playing))}document.querySelectorAll?.('[data-sentence-play]').forEach(button=>{const playing=speaking&&speechClip?.buttonId===button.id;button.innerHTML=playing?SENTENCE_STOP_ICON:SENTENCE_SPEAK_ICON;button.title=playing?'停止朗读':'朗读这一句';button.setAttribute('aria-pressed',String(!!playing))})}
function resetListenButton(){speaking=false;syncSpeechButtons()}
function selectedVoice(){return state.readVoice==='teacher'?'teacher':'child'}
function bookRecording(book){return book?.narrations?.[selectedVoice()]||book?.narration}
function bookPage(book,index,voice=selectedVoice()){const p=book.picturePages[index],v=p.voices?.[voice];if(!v)return p;return {...p,audioStart:v.audioStart,audioEnd:v.audioEnd,sentences:p.sentences?.map((s,i)=>({...s,...v.sentences?.[i]}))}}
function convertVoiceTime(book,time,from,to){if(from===to)return time;let index=0;for(let i=0;i<book.picturePages.length;i++){if(bookPage(book,i,from).audioStart<=time)index=i;else break}const a=bookPage(book,index,from),b=bookPage(book,index,to);let start=a.audioStart,end=a.audioEnd,destStart=b.audioStart,destEnd=b.audioEnd;for(let i=0;i<(a.sentences?.length||0);i++){const s=a.sentences[i],d=b.sentences?.[i];if(d&&s.audioStart<=time&&time<=s.audioEnd){start=s.audioStart;end=s.audioEnd;destStart=d.audioStart;destEnd=d.audioEnd;break}}const ratio=Math.max(0,Math.min(1,(time-start)/Math.max(.001,end-start)));return destStart+ratio*(destEnd-destStart)}
function voiceChoiceControl(){return `<select id="speech-voice" class="speech-voice" aria-label="朗读声音" title="选择美式女老师或美式小女孩声音"><option value="child" ${selectedVoice()==='child'?'selected':''}>小女孩</option><option value="teacher" ${selectedVoice()==='teacher'?'selected':''}>女老师</option></select>`}
function bindVoiceChoice(){const control=$('speech-voice');if(!control)return;control.onchange=()=>{const whole=!!speechClip?.wholeBook,playing=speaking,index=speechClip?.buttonId?.match(/^sentence-play-(\d+)$/)?.[1];stopSpeech();state.readVoice=control.value==='teacher'?'teacher':'child';save();if(!active)return;renderPictureReader();if(playing){if(whole)speakBook();else if(index!==undefined){const pair=pictureSentencePairs(page)[Number(index)];speak(pair.en,{audioStart:pair.audioStart,audioEnd:pair.audioEnd,buttonId:'sentence-play-'+index})}else speak(active.picturePages[page].text)}}}
function saveBookAudioPosition(){if(active&&speechClip?.wholeBook&&narrationPlayer){state.bookAudio??={};state.bookAudio[active.id]=Math.max(0,convertVoiceTime(active,narrationPlayer.currentTime,selectedVoice(),'child'));save()}}
function speakBook(){const book=active;if(!book?.picturePages?.length)return;if(speechClip?.wholeBook&&narrationPlayer){if(speaking){saveBookAudioPosition();clearTimeout(audioStopTimer);audioStopTimer=null;narrationPlayer.pause();speaking=false;syncSpeechButtons();return}speaking=true;narrationPlayer.playbackRate=state.readSpeed==='slow'?(bookRecording(book)?.slowRate||.8):1;syncSpeechButtons();narrationPlayer.play().catch(()=>{speaking=false;syncSpeechButtons();toast('请再点一次继续朗读')});return}const readingPages=book.picturePages.map((p,i)=>bookPage(book,i)).filter((p,i)=>p.text.trim()&&(p.layout==='reflow'||book.id==='a-tiny-seed'&&i>0&&i<book.picturePages.length-1)),last=readingPages[readingPages.length-1]||bookPage(book,book.picturePages.length-1);let start=convertVoiceTime(book,Number(state.bookAudio?.[book.id])||0,'child',selectedVoice());if(start>=last.audioEnd-.1)start=0;page=0;for(let i=0;i<book.picturePages.length;i++){if(bookPage(book,i).audioStart<=start)page=i;else break}renderPictureReader();speak([book.picturePages[0].text,...readingPages.filter(p=>p.audioEnd>start).map(p=>p.text)].filter(Boolean).join(' '),{audioStart:start,audioEnd:last.audioEnd,buttonId:'listen-book',wholeBook:true})}
function followBookAudio(player){if(!speechClip?.wholeBook)return;let index=0;for(let i=0;i<active.picturePages.length;i++){if(player.currentTime>=bookPage(active,i).audioStart)index=i;else break}if(index!==page){page=index;renderPictureReader(true)}}
function stopSpeech(){saveBookAudioPosition();speechGeneration++;clearTimeout(audioStopTimer);audioStopTimer=null;speechClip=null;if(narrationPlayer){narrationPlayer.pause();narrationPlayer.onended=narrationPlayer.onerror=narrationPlayer.ontimeupdate=narrationPlayer.onloadedmetadata=narrationPlayer.onplaying=narrationPlayer.onratechange=narrationPlayer.onseeked=narrationPlayer.onwaiting=null;}if('speechSynthesis'in window)speechSynthesis.cancel();resetListenButton()}
function applySettings(){document.body.classList.toggle('night',state.night);document.documentElement.style.setProperty('--read-size',state.size+'px')}

function speechSpeedControl(){return `<select id="speech-speed" class="speech-speed" aria-label="朗读速度" title="全局朗读速度；慢速保持自然音高"><option value="normal" ${state.readSpeed!=='slow'?'selected':''}>正常</option><option value="slow" ${state.readSpeed==='slow'?'selected':''}>慢速</option></select>`}
function bindSpeechSpeed(){const control=$('speech-speed');if(control)control.onchange=()=>{state.readSpeed=control.value==='slow'?'slow':'normal';save();if(speaking||speechClip?.wholeBook&&narrationPlayer){if(narrationPlayer)narrationPlayer.playbackRate=state.readSpeed==='slow'?(bookRecording(active)?.slowRate||.8):1;else speak(speechText,speechClip)}}}
function americanFemaleVoice(){const voices=speechSynthesis.getVoices(),us=voices.filter(v=>/^en[-_]US$/i.test(v.lang));return (selectedVoice()==='teacher'?us.find(v=>/Jenny|Aria|Samantha|Zira/i.test(v.name)):us.find(v=>/Ana/i.test(v.name)))||us.find(v=>/Samantha|Zira|Aria|Jenny|Michelle|Ava|Allison|Joanna|Salli|Susan|female/i.test(v.name)&&v.localService)||us.find(v=>/Samantha|Zira|Aria|Jenny|Michelle|Ava|Allison|Joanna|Salli|Susan|female/i.test(v.name))||us.find(v=>v.localService)||us[0]}
function speakWithDevice(text,token){if(!('speechSynthesis'in window)){resetListenButton();toast('当前设备暂时无法朗读');return}const u=new SpeechSynthesisUtterance(text);u.lang='en-US';u.rate=state.readSpeed==='slow'?.4:.9;const voice=americanFemaleVoice();if(voice)u.voice=voice;u.onend=u.onerror=()=>{if(token===speechGeneration)resetListenButton()};speechSynthesis.speak(u)}
function warmPageAudio(){if(!navigator.onLine||typeof PAGE_AUDIO==='undefined'||!active?.picturePages)return;const item=bookPage(active,page),recording=bookRecording(active),clip=PAGE_AUDIO[recording?.src]?.find(p=>p.start<=item.audioStart+.005&&p.end>=item.audioEnd-.005);if(clip)fetch(clip.src).catch(()=>{})}
function prepareNextSentence(player,item,clip,pageRecording=null){
 if(!clip?.buttonId?.startsWith('sentence-play-')||!active?.picturePages)return;
 const pairs=active.picturePages.flatMap((p,i)=>bookPage(active,i).sentences||[]),next=pairs.find(pair=>Number.isFinite(pair.audioStart)&&pair.audioStart>=item.audioEnd-.02&&pair.audioStart>item.audioStart);
 if(next&&player.readyState>=1){if(pageRecording&&next.audioStart>=pageRecording.end-.02){const following=PAGE_AUDIO[bookRecording(active).src]?.find(p=>p.start>=pageRecording.end-.02);if(following)fetch(following.src).catch(()=>{});return}try{player.currentTime=pageRecording?next.audioStart-pageRecording.start+pageRecording.lead:next.audioStart}catch{}}
}
function speak(text,clip=null){stopSpeech();speechText=text;speechClip=clip;speaking=true;const b=$('listen');if(b)b.textContent='停止朗读';if(clip?.buttonId){const button=$(clip.buttonId);if(button){if(clip.wholeBook)button.textContent='暂停朗读';else{button.innerHTML=SENTENCE_STOP_ICON;button.title='停止朗读'}button.setAttribute('aria-pressed','true')}}const token=speechGeneration,originalItem=clip||(active?.picturePages?bookPage(active,page):null),recording=bookRecording(active),pageRecording=!clip?.wholeBook&&!clip?.fullRecording&&navigator.onLine&&typeof PAGE_AUDIO!=='undefined'&&recording?PAGE_AUDIO[recording.src]?.find(p=>originalItem&&originalItem.audioStart>=p.start-.005&&originalItem.audioEnd<=p.end+.005):null,item=pageRecording?{...originalItem,audioStart:Math.max(0,originalItem.audioStart-pageRecording.start+pageRecording.lead),audioEnd:originalItem.audioEnd-pageRecording.start+pageRecording.lead}:originalItem;if(recording&&(clip||item?.text===text)&&Number.isFinite(item.audioStart)&&Number.isFinite(item.audioEnd)){
 const source=new URL(pageRecording?.src||recording.src,location.href).href;const player=narrationPlayer||new Audio();narrationPlayer=player;if(player.src!==source){player.src=source}player.preload='auto';player.playbackRate=state.readSpeed==='slow'?(recording.slowRate||.8):1;player.preservesPitch=true;player.webkitPreservesPitch=true;
 const finish=()=>{if(token!==speechGeneration)return;if(clip?.wholeBook&&active){delete state.bookAudio?.[active.id];save()}speechClip=null;clearTimeout(audioStopTimer);audioStopTimer=null;player.pause();resetListenButton();prepareNextSentence(player,originalItem,clip,pageRecording)};
 const schedule=()=>{clearTimeout(audioStopTimer);if(token!==speechGeneration||player.paused)return;const remaining=item.audioEnd-player.currentTime;if(remaining<=0){finish();return}audioStopTimer=setTimeout(()=>{if(token!==speechGeneration||narrationPlayer!==player)return;if(player.currentTime>=item.audioEnd-.02)finish();else schedule()},remaining/player.playbackRate*1000)};
 const seek=()=>{if(token===speechGeneration&&Math.abs(player.currentTime-item.audioStart)>.08)player.currentTime=item.audioStart};player.onloadedmetadata=seek;if(player.readyState>=1)seek();player.ontimeupdate=()=>{if(!speaking)return;if(player.currentTime>=item.audioEnd)finish();else{followBookAudio(player);schedule()}};player.onplaying=player.onratechange=player.onseeked=schedule;player.onwaiting=()=>clearTimeout(audioStopTimer);player.onended=finish;
 const fallback=()=>{if(token!==speechGeneration)return;if(pageRecording){speak(text,{...originalItem,fullRecording:true});return}clearTimeout(audioStopTimer);player.pause();player.onerror=null;narrationPlayer=null;toast('音频暂时无法播放，改用设备朗读');speakWithDevice(text,token)};player.onerror=fallback;player.play().catch(error=>{if(token!==speechGeneration||narrationPlayer!==player)return;if(error.name==='NotAllowedError'){finish();toast('请再点一次“听这一页”')}else fallback()});
 }else speakWithDevice(text,token)}
function readingLevel(book){return book.readingLevel||(book.id==='a-tiny-seed'?{level:3,source:'Global Storybooks'}:null);}
function lexileLabel(book){const rating=readingLevel(book);return (book.originalReader||book.adaptedReader)?'简明英文 · 蓝思值未测评':rating?'阅读难度：Level '+rating.level+' · '+rating.source:'阅读难度：未分级';}
function lexileInfo(book){if(book.adaptedReader)return '<p>经典小说简明英文改写 · 蓝思值未测评</p><p>'+(book.chapters?.length||0)+' 章 · '+escapeHTML(book.translationNote||'主要故事线的节选改写')+' 常用词、短句，适合在逐句翻译辅助下阅读；不是官方分级版本。</p>';if(book.originalReader)return '<p>原创简明英文读物 · 无正式蓝思值</p><p>依据公开资料核实事实，使用短句和常用词。未参加官方难度测评。</p>';const rating=readingLevel(book);return '<p>'+escapeHTML(lexileLabel(book))+'</p><p>'+(rating?.source==='StoryWeaver'?'StoryWeaver 原站分级：Level 1–4，从初学阅读到熟练阅读。':'采用本书原来源的阅读分级。')+'级别不对应中国年级，也不是蓝思值。</p>';}
function bookStatus(s){const p=state.progress[s.id];return p?.done?'已读完':p?'读到第 '+(p.page+1)+' 页':'还没开始'}
const SHELF_DIFFICULTIES={starter:'入门',developing:'进阶',challenge:'挑战'};
let shelfFilters={difficulty:'all',topic:'all'};
function shelfBookTitle(book){return book.titleZh||book.title}
function shelfClassification(book){const level=SHELF_DIFFICULTIES[book.shelfDifficulty]||'待分类';return `<div class="book-tags"><span class="difficulty-tag">${escapeHTML(level)}</span>${(book.topics||[]).map(t=>`<span>${escapeHTML(t)}</span>`).join('')}</div>`}
function shelfFilterControls(all,list){const topics=[...new Set(all.flatMap(b=>b.topics||[]))].sort((a,b)=>a.localeCompare(b,'zh-CN'));return `<section class="shelf-filters" aria-label="图书筛选"><div class="shelf-filter-row"><label>阅读难度<select id="difficulty-filter"><option value="all">全部难度</option>${Object.entries(SHELF_DIFFICULTIES).map(([id,title])=>`<option value="${id}" ${shelfFilters.difficulty===id?'selected':''}>${title}</option>`).join('')}</select></label><label>内容主题<select id="topic-filter"><option value="all">全部主题</option>${topics.map(t=>`<option value="${escapeHTML(t)}" ${shelfFilters.topic===t?'selected':''}>${escapeHTML(t)}</option>`).join('')}</select></label><button id="reset-shelf-filters" class="quiet">显示全部</button><span class="filter-count" role="status">找到 ${list.length} 本</span></div><details class="difficulty-help"><summary>难度怎么分？</summary><p>入门：短篇、常用词和较短的句子。进阶：叙述更长，情节和词汇更丰富。挑战：长篇阅读或更复杂的句子与表达。按当前英文版本作本站参考分类，简写版可能比原著容易；不对应中国年级或蓝思值，也不是原站官方分级。原站级别仍单独显示。</p></details></section>`}
function globalSpeechControls(){return `<section class="global-speech-settings" aria-label="全局朗读设置"><strong>朗读设置</strong><label>声音${voiceChoiceControl()}</label><label>语速${speechSpeedControl()}</label><span>自动保存，适用于所有书</span></section>`}
function showSpeechSettings(){$('speech-settings-content').innerHTML=globalSpeechControls();bindVoiceChoice();bindSpeechSpeed();$('speech-dialog').showModal()}
function shelf(tab='all'){window.pictureResize?.disconnect();document.body.classList.remove('picture-mode');stopSpeech();active=null;view=tab;const all=stories(),done=all.filter(s=>state.progress[s.id]?.done).length,last=all.find(s=>s.id===state.last&&!state.progress[s.id]?.done);let list=tab==='done'?all.filter(s=>state.progress[s.id]?.done):all;list=list.filter(s=>(shelfFilters.difficulty==='all'||s.shelfDifficulty===shelfFilters.difficulty)&&(shelfFilters.topic==='all'||s.topics?.includes(shelfFilters.topic)));
 $('app').innerHTML=`<div class="library-top"><div><span class="eyebrow">YOUR LITTLE READING WORLD</span><h1>我的英文书架</h1><p class="intro">选一个故事，开始今天的冒险。</p></div><span class="counter">已读完 ${done} / ${all.length} 篇</span></div>${last?`<section class="continue"><div><span class="eyebrow">KEEP READING</span><h2>${escapeHTML(shelfBookTitle(last))}</h2>${last.titleZh?`<p class="book-title-en" lang="en">${escapeHTML(last.title)}</p>`:''}<p>${bookStatus(last)} · ${last.kind==='picture'?'绘本':'Minecraft Stories'}</p></div><button data-open="${escapeHTML(last.id)}">继续阅读</button></section>`:''}<nav class="tabs" aria-label="书架分类"><button data-tab="all" class="${tab==='all'?'selected':''}">全部故事 ${all.length}</button><button data-tab="done" class="${tab==='done'?'selected':''}">已读完 ${done}</button><button data-tab="words" class="${tab==='words'?'selected':''}">生词本 ${state.words.length}</button></nav>${tab!=='words'?shelfFilterControls(all,list):''}${tab==='words'?renderWords():list.length?`<div class="grid">${list.map(s=>{const p=state.progress[s.id],progress=p?.done?100:p?Math.round(p.page/pages(s).length*100):0;const wc=s.paragraphs.join(' ').split(/\s+/).length;return `<button class="book" data-open="${escapeHTML(s.id)}"><div class="cover">${s.picturePages?`<img class="cover-art" src="${escapeHTML(s.picturePages[0].image)}" alt="">`:""}<div class="cover-top"><span>${s.adaptedReader?'CLASSIC ADVENTURES':s.originalReader?'TRUE EXPERIENCES':s.kind==='picture'?'PICTURE BOOK':s.chapter?'MINECRAFT STORIES':'MY STORIES'}</span><span>ENGLISH</span></div><span class="chapter">${s.kind==='picture'?(readingLevel(s)?'L'+readingLevel(s).level:''):String(s.chapter||'').padStart(2,'0')}</span><div class="cover-title">${escapeHTML(s.title)}</div></div><div class="book-info"><h3>${escapeHTML(shelfBookTitle(s))}</h3>${s.titleZh?`<p class="book-title-en" lang="en">${escapeHTML(s.title)}</p>`:''}${shelfClassification(s)}<p class="lexile-label">${escapeHTML(lexileLabel(s))}</p>${s.synopsis?`<p class="book-synopsis">${escapeHTML(s.synopsis)}</p>`:''}<div class="book-meta"><span>${wc} 词 · ${pages(s).length} 页</span><span>${bookStatus(s)}</span></div><div class="progress"><span style="width:${progress}%"></span></div></div></button>`}).join('')}</div>`:`<p class="empty">${tab==='done'?'暂时没有符合筛选条件的已读图书。':'暂时没有符合筛选条件的图书。'}可以调整分类，或点击“显示全部”。</p>`}`;
 bindVoiceChoice();bindSpeechSpeed();const difficulty=$('difficulty-filter'),topic=$('topic-filter'),reset=$('reset-shelf-filters');if(difficulty)difficulty.onchange=()=>{shelfFilters.difficulty=difficulty.value;shelf(tab)};if(topic)topic.onchange=()=>{shelfFilters.topic=topic.value;shelf(tab)};if(reset)reset.onclick=()=>{shelfFilters={difficulty:'all',topic:'all'};shelf(tab)};
 $('app').querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>openStory(b.dataset.open));$('app').querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>shelf(b.dataset.tab));$('app').querySelectorAll('[data-vocab]').forEach(b=>b.onclick=()=>showWord(b.dataset.vocab));window.scrollTo(0,0)}
function renderWords(){return state.words.length?`<div class="word-grid">${state.words.map(w=>`<button class="word-card" data-vocab="${escapeHTML(w)}"><strong>${escapeHTML(w)}</strong><span>${escapeHTML(data.glossary[w]||'可以请家长一起查词')}</span></button>`).join('')}</div>`:'<p class="empty">阅读时点一个单词，再点“加入生词本”。你的新单词就会留在这里。</p>'}
function findReadingBook(id){return stories().find(s=>s.id===id)||data.archivedStories?.find(s=>s.id===id)}
function openStory(id){active=findReadingBook(id);if(!active)return;page=Math.min(state.progress[id]?.page||0,pages(active).length-1);state.last=id;recordReading(active,page);renderReader()}
function tokenize(p){return p.split(/([A-Za-zÀ-ÖØ-öø-ÿ]+(?:['’][A-Za-zÀ-ÖØ-öø-ÿ]+)?)/).map(t=>/^[A-Za-zÀ-ÖØ-öø-ÿ]/.test(t)?`<span class="word ${data.glossary[t.toLowerCase()]?'known':''}" tabindex="0" role="button" data-word="${escapeHTML(t)}" aria-label="查看 ${escapeHTML(t)} 的释义">${escapeHTML(t)}</span>`:escapeHTML(t)).join('')}
function renderTextReader(){stopSpeech();const ps=pages(active);state.progress[active.id]={...state.progress[active.id],page};save();$('app').innerHTML=`<div class="reader-top"><button id="back" class="quiet">回到书架</button><div class="reader-tools"><button id="smaller" aria-label="减小字号">A−</button><button id="larger" aria-label="增大字号">A＋</button><button id="theme">${state.night?'白天':'夜间'}</button><button id="listen">听这一页</button></div></div><article class="reading-shell"><div class="story-heading"><span class="eyebrow">${active.chapter?'MINECRAFT · CHAPTER '+String(active.chapter).padStart(2,'0'):'MY STORY'}</span><h1>${escapeHTML(active.title)}</h1><p class="reader-hint">点单词查释义 · 虚线标出了故事中的重点词</p></div><div class="story-text">${ps[page].map(p=>'<p>'+tokenize(p)+'</p>').join('')}</div><div class="reader-bottom"><button id="prev" class="quiet" ${page===0?'disabled':''}>上一页</button><span class="page-number">${page+1} / ${ps.length}</span><button id="next">${page===ps.length-1?'读完了':'下一页'}</button></div></article><div class="reader-progress"><div class="progress"><span style="width:${Math.round((page+1)/ps.length*100)}%"></span></div></div>`;
 bindSpeechSpeed();$('back').onclick=()=>shelf();$('prev').onclick=()=>{page--;renderReader();window.scrollTo(0,0)};$('next').onclick=()=>{if(page===ps.length-1)active.quiz?quiz():complete();else{page++;renderReader();window.scrollTo(0,0)}};$('smaller').onclick=()=>{state.size=Math.max(19,state.size-2);applySettings();save()};$('larger').onclick=()=>{state.size=Math.min(37,state.size+2);applySettings();save()};$('theme').onclick=()=>{state.night=!state.night;applySettings();save();$('theme').textContent=state.night?'白天':'夜间'};$('listen').onclick=()=>speaking?stopSpeech():speak(ps[page].join(' '));$('app').querySelectorAll('[data-word]').forEach(w=>{w.onclick=()=>showWord(w.dataset.word);w.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();showWord(w.dataset.word)}}})}
function showWord(w){selectedWord=w.toLowerCase();$('word-title').textContent=w;$('meaning').textContent=data.glossary[selectedWord]||'这篇故事没有附这个词的释义。你可以先结合上下文猜一猜，也可以加入生词本，和家长一起查。';$('save-word').textContent=state.words.includes(selectedWord)?'移出生词本':'加入生词本';$('word-dialog').showModal()}
function quiz(){stopSpeech();const q=active.quiz;$('app').innerHTML=`<button id="back-read" class="quiet">返回故事</button><article class="reading-shell"><span class="eyebrow">ONE LITTLE CHECK</span><h1>你读懂了吗？</h1><h2>${escapeHTML(q.question)}</h2><div class="quiz-options">${q.options.map((o,i)=>`<button data-answer="${i}">${escapeHTML(o)}</button>`).join('')}</div><p id="feedback" class="feedback">选一个答案。答错了也可以再读一遍。</p><button id="finish" hidden>完成阅读</button></article>`;$('back-read').onclick=renderReader;$('app').querySelectorAll('[data-answer]').forEach(b=>b.onclick=()=>{const correct=Number(b.dataset.answer)===q.answer;b.classList.add(correct?'correct':'wrong');$('feedback').textContent=correct?'答对了！这个故事已经读懂啦。':'再想一想，也可以返回故事找线索。';if(correct)$('finish').hidden=false});$('finish').onclick=complete;window.scrollTo(0,0)}
function complete(){stopSpeech();state.progress[active.id]={page:pages(active).length-1,done:true,completedAt:new Date().toISOString()};save();$('app').innerHTML=`<article class="reading-shell finish"><div class="badge">✦</div><span class="eyebrow">STORY COMPLETE</span><h1>又读完了一个故事！</h1><p class="feedback">${escapeHTML(active.title)}</p><button id="finished-back">回到书架</button></article>`;$('finished-back').onclick=()=>shelf();window.scrollTo(0,0)}
document.querySelectorAll('.dialog-close').forEach(b=>b.onclick=()=>b.closest('dialog').close());$('home').onclick=()=>shelf();$('parents').onclick=()=>{$('parent-dialog').showModal()};$('say-word').onclick=()=>speak(selectedWord);$('save-word').onclick=()=>{if(state.words.includes(selectedWord))state.words=state.words.filter(w=>w!==selectedWord);else state.words.push(selectedWord);save();$('save-word').textContent=state.words.includes(selectedWord)?'移出生词本':'加入生词本';if(!active)shelf(view)};
$('backup').onclick=()=>{const blob=new Blob([JSON.stringify({format:'silva-reader-backup',version:1,state},null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='silva-reading-backup.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};
$('restore').onchange=async e=>{try{const file=e.target.files[0];if(!file)return;if(file.size>3000000)throw Error();const b=JSON.parse(await file.text()),s=b.state;if(b.format!=='silva-reader-backup'||!s||!Array.isArray(s.words)||!s.words.every(w=>typeof w==='string')||!Array.isArray(s.custom)||!s.custom.every(x=>typeof x.id==='string'&&typeof x.title==='string'&&Array.isArray(x.paragraphs)&&x.paragraphs.length&&x.paragraphs.every(p=>typeof p==='string'))||!s.progress||typeof s.progress!=='object')throw Error();if(!confirm('恢复备份将替换这台设备上的阅读记录和自建故事。继续吗？'))return;state={history:s.history&&typeof s.history==='object'?s.history:{},notes:s.notes&&typeof s.notes==='object'?s.notes:{},progress:s.progress,words:s.words,custom:s.custom,size:Math.max(19,Math.min(37,Number(s.size)||25)),night:!!s.night,readSpeed:s.readSpeed==='slow'?'slow':'normal',readVoice:s.readVoice==='teacher'?'teacher':'child',bookAudio:s.bookAudio&&typeof s.bookAudio==='object'?s.bookAudio:{},last:s.last};save();applySettings();$('parent-dialog').close();shelf();toast('备份已恢复')}catch{$('parent-message').textContent='无法读取备份，请选择本工具导出的备份文件。'}finally{e.target.value=''}};
async function init(){applySettings();try{const r=await fetch('stories.json');if(!r.ok)throw Error();data=await r.json();shelf();if('serviceWorker'in navigator){const hadController=!!navigator.serviceWorker.controller;let reloading=false;const reg=await navigator.serviceWorker.register('sw.js',{updateViaCache:'none'});reg.update().catch(()=>{});await navigator.serviceWorker.ready;const ready=()=>{const sw=navigator.serviceWorker.controller||reg.active;if(sw)sw.postMessage({type:'CHECK_OFFLINE'})};navigator.serviceWorker.addEventListener('message',e=>{if(e.data?.type==='OFFLINE_READY')$('offline').textContent='故事已保存，可离线阅读';if(e.data?.type==='OFFLINE_FAILED')$('offline').textContent='离线保存未完成，请联网重试'});navigator.serviceWorker.addEventListener('controllerchange',()=>{if(hadController&&!reloading){reloading=true;location.reload()}else ready()});ready()}else $('offline').textContent='请用 Safari 打开以保存离线故事';}catch{$('app').innerHTML='<div class="empty">故事暂时无法加载。首次使用请联网打开；如果已经保存离线故事，请重新打开主屏幕上的工具。</div>';$('offline').textContent='故事未加载'}}init();

function shareSite(){$('system-share').hidden=typeof navigator.share!=='function';$('share-message').textContent='复制链接后，打开微信，粘贴发送给朋友或群聊。';$('share-dialog').showModal()}
async function systemShareSite(){try{await navigator.share({title:'Silva Reads · 英文阅读书架',text:'一起来读英文故事：逐句翻译、朗读和阅读笔记。',url:'https://myread.ccwu.cc/'})}catch(e){if(e.name!=='AbortError')$('share-message').textContent='可以点击“复制链接”，再到微信粘贴发送。'}}
async function copySiteLink(){try{await navigator.clipboard.writeText('https://myread.ccwu.cc/');$('share-message').textContent='链接已复制，打开微信粘贴发送即可。'}catch{const input=$('share-link');input.focus();input.select();input.setSelectionRange(0,input.value.length);$('share-message').textContent='请长按或使用复制，将选中的链接发到微信。'}}
