function renderReader(){if(active?.kind==='picture')renderPictureReader();else renderTextReader()}
function renderPictureReader(){
 stopSpeech();const item=active.picturePages[page],last=page===active.picturePages.length-1,reflow=active.id==='a-tiny-seed'&&page>0&&!last;state.progress[active.id]={...state.progress[active.id],page};save();
 $('app').innerHTML=`<div class="reader-top"><button id="back" class="quiet">回到书架</button><div class="reader-tools"><button id="smaller" aria-label="减小字号">A−</button><button id="larger" aria-label="增大字号">A＋</button><button id="listen">听这一页</button></div></div><article class="reading-shell picture-shell"><div class="story-heading"><span class="eyebrow">PICTURE BOOK · ENGLISH</span><h1>${escapeHTML(active.title)}</h1><p class="reader-hint">左右滑动翻页，也可以点图片两侧箭头 · A＋放大英文</p></div><div id="picture-surface" class="picture-surface"><div class="picture-art ${reflow?'enlarged-art':''}"><img class="picture-page" src="${escapeHTML(item.image)}" alt="${escapeHTML(active.title)} 第 ${page+1} 页"><button id="art-prev" class="art-arrow art-prev" aria-label="图片上一页" ${page===0?'disabled':''}>‹</button><button id="art-next" class="art-arrow art-next" aria-label="${last?'完成绘本':'图片下一页'}">›</button></div>${reflow?`<div class="storybook-text story-text"><p>${tokenize(item.text)}</p></div>`:''}</div><div class="reader-bottom picture-navigation"><button id="prev" class="quiet" ${page===0?'disabled':''}>上一页</button><span class="page-number">${page+1} / ${active.picturePages.length}</span><button id="next">${last?'读完了':'下一页'}</button></div>${reflow?'':`<details class="picture-text"><summary>英文原文与点读</summary><div class="story-text"><p>${tokenize(item.text)}</p></div></details>`}<footer class="attribution">${escapeHTML(active.credits)}<br><a href="https://creativecommons.org/licenses/by/4.0/" target="_blank" rel="noopener">CC BY 4.0</a> · <a href="${escapeHTML(active.sourceUrl)}" target="_blank" rel="noopener">来源</a> · <a href="${escapeHTML(active.original)}" target="_blank" rel="noopener">英文原版 PDF</a><br>阅读视图放大原插画并重新排版原文；英文原版 PDF 保持不变。</footer></article>`;
 const previous=()=>{if(page===0)return;page--;renderPictureReader();window.scrollTo(0,0)},next=()=>{if(last)complete();else{page++;renderPictureReader();window.scrollTo(0,0)}};
 $('back').onclick=()=>shelf();$('prev').onclick=previous;$('next').onclick=next;$('art-prev').onclick=previous;$('art-next').onclick=next;
 let start=null;const surface=$('picture-surface');surface.addEventListener('touchstart',e=>{start=e.touches.length===1?{x:e.touches[0].clientX,y:e.touches[0].clientY}:null},{passive:true});surface.addEventListener('touchmove',e=>{if(e.touches.length!==1)start=null},{passive:true});surface.addEventListener('touchcancel',()=>start=null,{passive:true});surface.addEventListener('touchend',e=>{if(!start||e.touches.length)return;const t=e.changedTouches[0],dx=t.clientX-start.x,dy=t.clientY-start.y;start=null;if(Math.abs(dx)>70&&Math.abs(dx)>Math.abs(dy)*1.5){if(dx<0)next();else previous()}},{passive:true});
 $('listen').onclick=()=>speaking?stopSpeech():speak(item.text);$('smaller').onclick=()=>{state.size=Math.max(19,state.size-2);applySettings();save()};$('larger').onclick=()=>{state.size=Math.min(37,state.size+2);applySettings();save()};$('app').querySelectorAll('[data-word]').forEach(w=>{w.onclick=()=>showWord(w.dataset.word);w.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();showWord(w.dataset.word)}}});
}

