const pictureTranslations=[[],["在东非肯尼亚山的山坡上，有一个村庄，一个小女孩和妈妈一起在田里干活。","她的名字叫旺加里。"],["旺加里喜欢待在户外。","在家里的菜园中，她用砍刀翻松泥土。","她把小小的种子按进温暖的土里。"],["她一天中最喜欢的时刻是日落之后。","当天色暗得看不清植物时，旺加里就知道该回家了。","她沿着田间狭窄的小路走，途中还要渡过河流。"],["旺加里是个聪明的孩子，迫不及待地想去上学。","可是，爸爸妈妈希望她留在家里帮忙。","七岁时，哥哥说服了父母，让她去上学。"],["她喜欢学习！","每读一本书，旺加里就学到更多知识。","她在学校表现非常好，因此受邀去美国留学。","旺加里很兴奋！","她想更多地了解这个世界。"],["在美国的大学里，旺加里学到了许多新知识。","她研究植物以及它们如何生长。","她也想起了自己的成长经历：在美丽的肯尼亚森林里，和兄弟们一起在树荫下玩游戏。"],["她学得越多，就越意识到自己热爱肯尼亚人民。","她希望他们幸福、自由。","她学得越多，就越想念非洲的家乡。"],["完成学业后，她回到了肯尼亚。","可是，她的祖国已经变了。","大片农场遍布这片土地。","妇女们没有木柴生火做饭。","人们很贫穷，孩子们饿着肚子。"],["旺加里知道该怎么做。","她教妇女们如何用种子种树。","妇女们卖掉树苗，用赚来的钱照顾家人。","妇女们非常高兴。","旺加里帮助她们感到自己有力量、很坚强。"],["随着时间流逝，新种的树长成了森林，河流又开始流淌。","旺加里的理念传遍了非洲。","如今，旺加里播下的种子已经长成了数百万棵树。"],["旺加里一直努力工作。","世界各地的人们注意到了她，并授予她一个著名的奖项。","这个奖叫诺贝尔和平奖，她是第一位获得这个奖的非洲女性。"],["旺加里于2011年去世，但每当我们看到一棵美丽的树，都可以想起她。"],[]];
function renderReader(){if(active?.kind==='picture')renderPictureReader();else renderTextReader()}
function renderPictureReader(){
 stopSpeech();window.pictureResize?.disconnect();document.body.classList.add('picture-mode');const item=active.picturePages[page],last=page===active.picturePages.length-1,reflow=active.id==='a-tiny-seed'&&page>0&&!last;state.progress[active.id]={...state.progress[active.id],page};recordReading(active,page);save();
 $('app').innerHTML=`<div class="reader-top fit-toolbar"><button id="back" class="quiet">回到书架</button><div class="reader-tools"><button id="book-info-button" aria-label="绘本信息">ⓘ</button><button id="smaller" aria-label="减小字号">A−</button><button id="larger" aria-label="增大字号">A＋</button><button id="sentence-translation" aria-pressed="${!!state.showTranslation}" ${reflow?'':'disabled'}>${state.showTranslation?'隐藏翻译':'逐句翻译'}</button><button id="listen">听这一页</button></div></div><article class="reading-shell picture-shell"><div class="fit-heading"><strong>${escapeHTML(active.title)}</strong><label class="fit-ratio">图文比例<input id="art-ratio" aria-label="图片所占比例" type="range" min="30" max="70" value="${state.artRatio||50}"></label><button id="write-note" class="quiet">写笔记</button><button id="auto-fit" class="quiet">自适应</button></div><div id="picture-surface" class="picture-surface ${reflow?'fit-reflow':'fit-original'}"><div class="picture-art ${reflow?'enlarged-art':''}"><div class="illustration-window"><img class="picture-page" src="${escapeHTML(item.image)}" alt="${escapeHTML(active.title)} 第 ${page+1} 页"></div></div>${reflow?`<div class="storybook-text story-text">${renderPictureSentences(item.text,page)}</div>`:''}</div><div class="reader-bottom picture-navigation"><button id="prev" class="quiet" ${page===0?'disabled':''}>上一页</button><span class="page-number">${page+1} / ${active.picturePages.length}</span><button id="next">${last?'读完了':'下一页'}</button></div><dialog id="book-info"><button class="dialog-close" id="close-book-info" aria-label="关闭">×</button><h2>绘本信息</h2>${lexileInfo(active)}<div class="attribution">${escapeHTML(active.credits)}<br><a href="https://creativecommons.org/licenses/by/4.0/" target="_blank" rel="noopener">CC BY 4.0</a> · <a href="${escapeHTML(active.sourceUrl)}" target="_blank" rel="noopener">来源</a> · <a href="${escapeHTML(active.original)}" target="_blank" rel="noopener">英文原版 PDF</a><br>阅读视图放大原插画并重新排版原文；英文原版 PDF 保持不变。</div></dialog></article>`;
 $('sentence-translation').onclick=()=>{state.showTranslation=!state.showTranslation;save();renderPictureReader()};const previous=()=>{if(page===0)return;page--;renderPictureReader();window.scrollTo(0,0)},next=()=>{if(last){document.body.classList.remove('picture-mode');complete();}else{page++;renderPictureReader();window.scrollTo(0,0)}};
 $('back').onclick=()=>{window.pictureResize?.disconnect();document.body.classList.remove('picture-mode');shelf()};$('book-info-button').onclick=()=>$('book-info').showModal();$('close-book-info').onclick=()=>$('book-info').close();$('prev').onclick=previous;$('next').onclick=next;
 let start=null;const surface=$('picture-surface');surface.addEventListener('touchstart',e=>{start=e.touches.length===1?{x:e.touches[0].clientX,y:e.touches[0].clientY}:null},{passive:true});surface.addEventListener('touchmove',e=>{if(e.touches.length!==1)start=null},{passive:true});surface.addEventListener('touchcancel',()=>start=null,{passive:true});surface.addEventListener('touchend',e=>{if(!start||e.touches.length)return;const t=e.changedTouches[0],dx=t.clientX-start.x,dy=t.clientY-start.y;start=null;if(Math.abs(dx)>70&&Math.abs(dx)>Math.abs(dy)*1.5){if(dx<0)next();else previous()}},{passive:true});
 $('listen').onclick=()=>speaking?stopSpeech():speak(item.text);$('smaller').onclick=()=>{state.size=Math.max(19,state.size-2);applySettings();save();fitPicturePage()};$('larger').onclick=()=>{state.size=Math.min(37,state.size+2);applySettings();save();fitPicturePage()};$('app').querySelectorAll('[data-word]').forEach(w=>{w.onclick=()=>showWord(w.dataset.word);w.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();showWord(w.dataset.word)}}});
 $('write-note').onclick=()=>showPageNote(active,page);const ratio=$('art-ratio');ratio.disabled=!reflow;ratio.oninput=()=>{state.artRatio=Number(ratio.value);save();fitPicturePage()};$('auto-fit').onclick=()=>{delete state.artRatio;save();fitPicturePage()};window.pictureResize=new ResizeObserver(fitPicturePage);window.pictureResize.observe(surface);fitPicturePage();
}


function fitPicturePage(){
 const surface=$('picture-surface');if(!surface)return;const text=surface.querySelector('.storybook-text'),art=surface.querySelector('.picture-art'),frame=surface.querySelector('.illustration-window');
 const count=text?.textContent.trim().split(/\s+/).length||0,ratio=state.artRatio||(state.showTranslation?(surface.clientWidth>surface.clientHeight?42:35):(surface.clientWidth>surface.clientHeight?50:count>70?42:54));surface.style.setProperty('--art-share',ratio+'%');$('art-ratio').value=ratio;
 if(text){const size=Math.floor(Math.min(art.clientWidth,art.clientHeight));frame.style.width=size+'px';frame.style.height=size+'px';let lo=12,hi=Math.min(44,state.size+7),best=lo;while(lo<=hi){const mid=Math.floor((lo+hi)/2);text.style.fontSize=mid+'px';if(text.scrollHeight<=text.clientHeight&&text.scrollWidth<=text.clientWidth){best=mid;lo=mid+1}else hi=mid-1}text.style.fontSize=best+'px';}
}


function renderPictureSentences(text,index){if(!state.showTranslation)return '<p>'+tokenize(text)+'</p>';const sentences=text.match(/[^.!?]+[.!?]+(?:[”"’])?|[^.!?]+$/g)||[text],zh=pictureTranslations[index]||[];return sentences.map((sentence,i)=>'<div class="sentence-pair"><p>'+tokenize(sentence.trim())+'</p><p class="sentence-zh" lang="zh-CN">'+escapeHTML(zh[i]||'')+'</p></div>').join('')}


let pageNoteContext=null;
function readingDate(){const d=new Date();return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0')}
function recordReading(book,index){state.history??={};const date=readingDate();state.history[date]??={};const entry=state.history[date][book.id]||{title:book.title,pages:[]};if(!entry.pages.includes(index))entry.pages.push(index);entry.lastAt=new Date().toISOString();state.history[date][book.id]=entry;}
function showPageNote(book,index){pageNoteContext={id:book.id,title:book.title,page:index};const note=state.notes?.[book.id+':'+index];$('note-heading').textContent=book.title+' · 第 '+(index+1)+' 页';$('note-body').value=note?.text||'';$('note-message').textContent='笔记保存在这台设备，可随阅读备份导出。';$('note-dialog').showModal();}
function savePageNote(){if(!pageNoteContext)return;const text=$('note-body').value.trim();state.notes??={};const key=pageNoteContext.id+':'+pageNoteContext.page;if(text)state.notes[key]={...pageNoteContext,text,updatedAt:new Date().toISOString()};else delete state.notes[key];save();$('note-dialog').close();toast(text?'笔记已保存':'已清空这页笔记');}
function showReadingRecords(){const history=state.history||{},notes=Object.values(state.notes||{}).filter(n=>n&&typeof n.text==='string'&&typeof n.id==='string'&&Number.isInteger(n.page)).sort((a,b)=>String(b.updatedAt).localeCompare(String(a.updatedAt)));$('record-content').innerHTML='<h3>阅读足迹</h3>'+ (Object.keys(history).length?Object.keys(history).sort().reverse().map(date=>'<section class="reading-day"><h4>'+escapeHTML(date)+'</h4>'+Object.entries(history[date]).map(([id,e])=>'<button class="record-entry quiet" data-record-book="'+escapeHTML(id)+'"><strong>'+escapeHTML(e.title)+'</strong><span>浏览 '+e.pages.length+' 页 · 第 '+e.pages.map(p=>p+1).sort((a,b)=>a-b).join('、')+' 页</span></button>').join('')+'</section>').join(''):'<p>开始阅读后，这里会按日期记录你看过的页。</p>')+'<h3>我的笔记</h3>'+(notes.length?notes.map(n=>'<button class="record-entry quiet" data-note-book="'+escapeHTML(n.id)+'" data-note-page="'+n.page+'"><strong>'+escapeHTML(n.title)+' · 第 '+(n.page+1)+' 页</strong><span class="note-preview">'+escapeHTML(n.text)+'</span></button>').join(''):'<p>阅读时点击“写笔记”，记下想法或新学到的内容。</p>');$('record-content').querySelectorAll('[data-record-book]').forEach(b=>b.onclick=()=>{if(!stories().some(s=>s.id===b.dataset.recordBook)){toast('这本书已不在当前书架');return}$('record-dialog').close();openStory(b.dataset.recordBook)});$('record-content').querySelectorAll('[data-note-book]').forEach(b=>b.onclick=()=>{const n=state.notes[b.dataset.noteBook+':'+b.dataset.notePage];$('record-dialog').close();showPageNote({id:n.id,title:n.title},n.page)});$('record-dialog').showModal();}
